export const QUOTES = [
  'The only way to do great work is to love what you do. — Steve Jobs',
  "Believe you can and you're halfway there. — Theodore Roosevelt",
  'It does not matter how slowly you go as long as you do not stop. — Confucius',
  "Everything you've ever wanted is on the other side of fear. — George Addair",
  'Success is not final, failure is not fatal: it is the courage to continue that counts. — Winston Churchill',
  'Hardships often prepare ordinary people for an extraordinary destiny. — C.S. Lewis',
  'The future belongs to those who believe in the beauty of their dreams. — Eleanor Roosevelt',
  "Don't count the days, make the days count. — Muhammad Ali",
  "Your time is limited, so don't waste it living someone else's life. — Steve Jobs",
  'The best way to predict the future is to create it. — Peter Drucker',
  'Seize the day. — Horace',
  'Innovation distinguishes between a leader and a follower. — Steve Jobs',
  'The only limit to our realization of tomorrow will be our doubts of today. — Franklin D. Roosevelt',
  'Do what you can, with what you have, where you are. — Theodore Roosevelt',
  'Be yourself; everyone else is already taken. — Oscar Wilde',
  'Happiness is not something ready made. It comes from your own actions. — Dalai Lama',
  'The purpose of our lives is to be happy. — Dalai Lama',
  'In the middle of every difficulty lies opportunity. — Albert Einstein',
  'What you get by achieving your goals is not as important as what you become by achieving your goals. — Zig Ziglar',
  "I have not failed. I've just found 10,000 ways that won't work. — Thomas Edison",
  'Action is the foundational key to all success. — Pablo Picasso',
  "It always seems impossible until it's done. — Nelson Mandela",
  'Quality is not an act, it is a habit. — Aristotle',
  'If you want to lift yourself up, lift up someone else. — Booker T. Washington',
  "Life is what happens when you're busy making other plans. — John Lennon",
  'The way to get started is to quit talking and begin doing. — Walt Disney',
  'Great things are done by a series of small things brought together. — Vincent Van Gogh',
  'The journey of a thousand miles begins with one step. — Lao Tzu',
  "You miss 100% of the shots you don't take. — Wayne Gretzky",
  "Whether you think you can or you think you can't, you're right. — Henry Ford",
  'Strive not to be a success, but rather to be of value. — Albert Einstein',
  'I attribute my success to this: I never gave or took any excuse. — Florence Nightingale',
  'You must be the change you wish to see in the world. — Mahatma Gandhi',
  'The only thing we have to fear is fear itself. — Franklin D. Roosevelt',
  'Do one thing every day that scares you. — Eleanor Roosevelt',
  'The mind is everything. What you think you become. — Buddha',
  'The best time to plant a tree was 20 years ago. The second best time is now. — Chinese Proverb',
  'An unexamined life is not worth living. — Socrates',
  'Eighty percent of success is showing up. — Woody Allen',
  "Winning isn't everything, but wanting to win is. — Vince Lombardi",
  'I am not a product of my circumstances. I am a product of my decisions. — Stephen Covey',
  'Every child is an artist. The problem is how to remain an artist once he grows up. — Pablo Picasso',
  'You can never cross the ocean until you have the courage to lose sight of the shore. — Christopher Columbus',
  'Either you run the day, or the day runs you. — Jim Rohn',
  'The two most important days in your life are the day you are born and the day you find out why. — Mark Twain',
  'Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it. — Johann Wolfgang von Goethe',
  'The best revenge is massive success. — Frank Sinatra',
  "People often say that motivation doesn't last. Well, neither does bathing. That's why we recommend it daily. — Zig Ziglar",
  "Life shrinks or expands in proportion to one's courage. — Anaïs Nin",
  "If you hear a voice within you say 'you cannot paint,' then by all means paint and that voice will be silenced. — Vincent Van Gogh",
  'There is only one way to avoid criticism: do nothing, say nothing, and be nothing. — Aristotle',
  'Ask and it will be given to you; search and you will find; knock and the door will be opened for you. — Jesus',
  'The only person you are destined to become is the person you decide to be. — Ralph Waldo Emerson',
  'Go confidently in the direction of your dreams. Live the life you have imagined. — Henry David Thoreau',
  'When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me. — Erma Bombeck',
  'Few things can help an individual more than to place responsibility on him, and to let him know that you trust him. — Booker T. Washington',
  'Certain things catch your eye, but pursue only those that capture the heart. — Ancient Indian Proverb',
  'Everything has beauty, but not everyone sees it. — Confucius',
  'Believe in yourself. Have faith in your abilities. — Norman Vincent Peale',
  'If you want to be happy, be. — Leo Tolstoy',
  'Life is 10% what happens to me and 90% of how I react to it. — Charles Swindoll',
  'Keep your face always toward the sunshine—and shadows will fall behind you. — Walt Whitman',
  'Change your thoughts and you change your world. — Norman Vincent Peale',
  'Success is walking from failure to failure with no loss of enthusiasm. — Winston Churchill',
  'The only place where success comes before work is in the dictionary. — Vidal Sassoon',
  'What lies behind us and what lies before us are tiny matters compared to what lies within us. — Ralph Waldo Emerson',
  'The power of imagination makes us infinite. — John Muir',
  "Try to be a rainbow in someone's cloud. — Maya Angelou",
  'You do not find a happy life. You make it. — Camilla Eyring Kimball',
  'The most wasted of all days is one without laughter. — Nicolas Chamfort',
  'Stay hungry, stay foolish. — Steve Jobs',
  'Spread love everywhere you go. Let no one ever come to you without leaving happier. — Mother Teresa',
  "Don't let yesterday take up too much of today. — Will Rogers",
  'The standard you walk past is the standard you accept. — David Hurley',
  'Your passion is waiting for your courage to catch up. — Isabelle Lafleche',
  'Do what you love and the money will follow. — Marsha Sinetar',
  'Start where you are. Use what you have. Do what you can. — Arthur Ashe',
  'Keep going. Everything you need will come to you at the perfect time. — Unknown',
  'Persistence guarantees that results are inevitable. — Paramahansa Yogananda',
  'The energy of the mind is the essence of life. — Aristotle',
  'A goal is a dream with a deadline. — Napoleon Hill',
  'Optimism is the faith that leads to achievement. — Helen Keller',
  'Dream big and dare to fail. — Norman Vaughan',
  "Opportunities don't happen. You create them. — Chris Grosser",
  "It's not whether you get knocked down, it's whether you get up. — Vince Lombardi",
  "If you are working on something that you really care about, you don't have to be pushed. The vision pulls you. — Steve Jobs",
  'Failure will never overtake me if my determination to succeed is strong enough. — Og Mandino',
  'We may encounter many defeats but we must not be defeated. — Maya Angelou',
  'Knowing is not enough; we must apply. Wishing is not enough; we must do. — Johann Wolfgang von Goethe',
  'Imagine your life is perfect in every respect; what would it look like? — Brian Tracy',
  'We generate fears while we sit. We overcome them by action. — Dr. Henry Link',
  'Security is mostly a superstition. Life is either a daring adventure or nothing. — Helen Keller',
  'The man who has confidence in himself gains the confidence of others. — Hasidic Proverb',
  'The only limit to our realization of tomorrow will be our doubts of today. — Franklin D. Roosevelt',
  'Creativity is intelligence having fun. — Albert Einstein',
  'What you lack in talent can be made up with desire, hustle and giving 110% all the time. — Don Zimmer',
  'Do what you can with all you have, wherever you are. — Theodore Roosevelt',
  'Develop success from failures. Discouragement and failure are two of the surest stepping stones to success. — Dale Carnegie',
  'If you can dream it, you can do it. — Walt Disney',
  'The difference between ordinary and extraordinary is that little extra. — Jimmy Johnson',
  'The secret of getting ahead is getting started. — Mark Twain',
];
